const express = require('express');
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes'); 
const funcionesSustantivasRoutes = require('./funcionesSustantivas.routes'); 
const actividadesRoutes = require('./actividades.routes');
const paraleloRoutes = require('./paralelo.routes');
const nivelRoutes = require('./nivel.routes');
const organizacionRoutes = require('./organizacion.routes');
const programasAnaliticosRoutes = require('./programasAnaliticos.routes');
const programaAnaliticoRoutes = require('./programaAnaliticoRoutes');
const datosAcademicosRoutes = require('./datosAcademicos.routes');
const profesorRoutes = require('./profesor.routes');
const syllabusRoutes = require('./syllabus.routes');
const asignaturaRoutes = require('./asignaturaRoutes');
const clasificaRoutes = require('./clasificacion.routes');
const periodoRoutes = require('./periodo.routes');
const mallaCurricularRoutes = require('./mallaCurricular.routes');
const mallaRoutes = require('./malla.routes');
const syllabusExtractionRoutes = require('./syllabusExtractionRoutes');
const comisionAcademicaRoutes = require('./comisionAcademica.routes');
const actividadesExtracurricularesRoutes = require('./actividadesExtracurriculares');
const rolRoutes = require('./rol.routes');
const usuariosRoutes = require('./usuarios.routes');
const facultadRoutes = require('./facultad.routes');
const carreraRoutes = require('./carrera.routes');
const router = express.Router();

module.exports = (app) => {
  app.use('/api', router);
  router.use('/auth', authRoutes);
  router.use('/users', userRoutes);
  router.use('/paralelo', paraleloRoutes);
  router.use('/paralelos', paraleloRoutes);
  router.use('/nivel', nivelRoutes);
  router.use('/niveles', nivelRoutes);
  router.use('/organizacion', organizacionRoutes);
  router.use('/organizacion_curricular', organizacionRoutes);
  router.use('/funciones-sustantivas', funcionesSustantivasRoutes); 
  router.use('/actividades', actividadesRoutes);
  router.use('/programas-analiticos', programasAnaliticosRoutes); 
  router.use('/programa-analitico', programaAnaliticoRoutes);
  router.use('/datos-academicos', datosAcademicosRoutes);
  router.use('/profesor', profesorRoutes);
  router.use('/profesores', profesorRoutes);
  router.use('/syllabi', syllabusRoutes);
  router.use('/asignaturas', asignaturaRoutes);
  router.use('/clasifica', clasificaRoutes);
  router.use('/periodo', periodoRoutes);
  router.use('/periodos', periodoRoutes);
  router.use('/malla-curricular', mallaCurricularRoutes);
  router.use('/mallas', mallaRoutes);
  router.use('/syllabus-extraction', syllabusExtractionRoutes);
  router.use('/comision-academica', comisionAcademicaRoutes);
  router.use('/actividades-extracurriculares', actividadesExtracurricularesRoutes);
  router.use('/roles', rolRoutes);
  router.use('/usuarios', usuariosRoutes);
  router.use('/facultades', facultadRoutes);
  router.use('/carreras', carreraRoutes);
};